{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bytedance.android",
    "module": "aabresguard-plugin",
    "version": "0.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "jvb6cslawjemvauxia35fvkwiy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.bytedance.android",
          "module": "aabresguard-core",
          "version": {
            "requires": "0.1.10"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "com.android.tools.build",
              "module": "gradle"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "aabresguard-plugin-0.1.10.jar",
          "url": "aabresguard-plugin-0.1.10.jar",
          "size": 21801,
          "sha512": "7f1e217a36250e25d448936c01f72556a3a625a526d66569ca8c29ba896ff4f1d6195dd11961330d220c68f388751aa11b1566b4727175a69ad90eb932c4f172",
          "sha256": "0743c11e6cc5b64dcd9a90b2af49e8d9b19c2905223aba8ff1ab0af13f14a11c",
          "sha1": "9120dbae1c7b6197c092dce3ece90e6adaa9e50a",
          "md5": "980c572b6d02053d79a24c8c67624d25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.61"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.3.61"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            }
          ]
        },
        {
          "group": "com.bytedance.android",
          "module": "aabresguard-core",
          "version": {
            "requires": "0.1.10"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "com.android.tools.build",
              "module": "gradle"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "aabresguard-plugin-0.1.10.jar",
          "url": "aabresguard-plugin-0.1.10.jar",
          "size": 21801,
          "sha512": "7f1e217a36250e25d448936c01f72556a3a625a526d66569ca8c29ba896ff4f1d6195dd11961330d220c68f388751aa11b1566b4727175a69ad90eb932c4f172",
          "sha256": "0743c11e6cc5b64dcd9a90b2af49e8d9b19c2905223aba8ff1ab0af13f14a11c",
          "sha1": "9120dbae1c7b6197c092dce3ece90e6adaa9e50a",
          "md5": "980c572b6d02053d79a24c8c67624d25"
        }
      ]
    }
  ]
}
